language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env: GO111MODULE=on

script:
  - go test -v ./... -race -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)